#ifndef STM32_RM0386_H
#define STM32_RM0386_H

#define STM32_RTC_EXTENDED
#define STM32_RTC_TAFCR_REG
#define STM32_RTC_ALARMB
#define STM32_RTC_BKP_WORDS (77)
#define STM32_RTC_COARSE_DIGITAL_CALIB
#define STM32_RTC_TAMPER1_MAPPING
#define STM32_RTC_ALARM_TYPE
#define STM32_RTC_TAMPER2

#define STM32_FLASH_PREFETCH
#define STM32_FLASH_CACHE
#define STM32_FLASH_SR_LAYOUT1
#define STM32_FLASH_PCROP
#define STM32_FLASH_MASS_ERASE_BANK2
#define STM32_FLASH_SNB_5BIT
#define STM32_FLASH_DUALBANK_BOOT_OPTION
#define STM32_FLASH_DUALBANK
#define STM32_FLASH_PROTECTION_MODE 
#define STM32_FLASH_OPTCR1_WRP

#define STM32_ADC_AWDCH17
#define STM32_ADC_AWDCH18
#define STM32_ADC_CSR_REG
#define STM32_ADC_COM_MULTI_MODE
#define STM32_ADC_COM_DELAY
#define STM32_ADC_COM_DMA
#define STM32_ADC_CDR_REG

#define STM32_GPIO_SPEED_HIGH
#define STM32_GPIO_SPEED_VERY_HIGH

#define STM32_RCC_AHB2
#define STM32_RCC_AHB2_REG
#define STM32_RCC_AHB3
#define STM32_RCC_CLOCK_48MHZ
#define STM32_RCC_CK48SEL_DCKCFGR
#define STM32_RCC_SAI1A
#define STM32_RCC_SAI1ASRC_LAYOUT2
#define STM32_RCC_SAI1B
#define STM32_RCC_SAI1BSRC_LAYOUT2
#define STM32_RCC_RNG_AHB2
#define STM32_RCC_PLLI2S
#define STM32_RCC_PLLI2S_FACTORQ
#define STM32_RCC_PLLI2S_FACTORR
#define STM32_RCC_PLLSAI
#define STM32_RCC_PLLSAI_FACTORP
#define STM32_RCC_PLLSAI_FACTORR
#define STM32_RCC_PLLI2S_DIVQ
#define STM32_RCC_PLLSAI_DIVQ
#define STM32_RCC_CLOCK_48MHZ
#define STM32_RCC_CLOCK_48MHZ_DCKCFGR_LAYOUT1
#define STM32_RCC_SDIOCK_DCKCFGR
#define STM32_RCC_CFGR
#define STM32_RCC_I2S

#define STM32_TIM_CC4NP

#define STM32_PWR_UD
#define STM32_PWR_ADC
#define STM32_PWR_VOS_2BIT
#define STM32_PWR_OD

#define STM32_SYSCFG_CMPCR
#define STM32_SYSCFG_FLASH_BANK_MODE
#define STM32_SYSCFG_MEMMODE_3BIT
#define STM32_SYSCFG_FMC
#define STM32_SYSCFG_FMC_SDRAM
#define STM32_SYSCFG_ADCxDC
#define STM32_SYSCFG_ADC1DC
#define STM32_SYSCFG_ADC2DC
#define STM32_SYSCFG_ADC3DC

#define STM32_LTDC_V1

#define STM32_DCMI_V1
#define STM32_DCMI_CR_EXTENDED

#define STM32_EXTI_ALLOWED_LINES_BITMASK (0x7fffff)

#define STM32_DMA_CHSEL_3BIT

#define STM32_DMA2D_V1

#define STM32_I2C_FILTER

#define STM32_RNG_V1
#define STM32_RNG_CK_ERRDE

#define STM32_CRYP_V1
#define STM32_CRYP_CS
#define STM32_CRYP_ALGO_EXTENDED

#define STM32_HASH_V1
#define STM32_HASH_ALGO_EXTENDED
#define STM32_HASH_HR_8BYTES
#define STM32_HASH_CSR_REG_COUNT (54)
#define STM32_HASH_KEY_TYPE

#define STM32_DAC_V1
#define STM32_DAC_CHANNEL2
#define STM32_DAC_TSEL_EXTENDED

#define STM32_QUADSPI_V1

#endif
