#ifndef STM32_RM0383_H
#define STM32_RM0383_H

#define STM32_RTC_EXTENDED
#define STM32_RTC_TAFCR_REG
#define STM32_RTC_ALARMB
#define STM32_RTC_BKP_WORDS (76)
#define STM32_RTC_COARSE_DIGITAL_CALIB
#define STM32_RTC_TAMPER1_MAPPING
#define STM32_RTC_ALARM_TYPE

#define STM32_GPIO_SPEED_FAST

#define STM32_RCC_AHB2
#define STM32_RCC_AHB2_REG
#define STM32_RCC_I2S
#define STM32_RCC_PLLI2S_FACTORM
#define STM32_RCC_PLLI2S_FACTORR
#define STM32_RCC_CFGR

#define STM32_TIM_CC4NP

#define STM32_PWR_LVDS
#define STM32_PWR_ADC
#define STM32_PWR_VOS_2BIT
#define STM32_PWR_FLASH

#define STM32_SYSCFG_CMPCR
#define STM32_SYSCFG_MEMMODE_2BIT
#define STM32_SYSCFG_PMC
#define STM32_SYSCFG_ADCxDC
#define STM32_SYSCFG_ADC1DC

#define STM32_EXTI_ALLOWED_LINES_BITMASK (0x67ffff)

#define STM32_DMA_CHSEL_3BIT

#define STM32_I2C_FILTER

#define STM32_FLASH_PCROP
#define STM32_FLASH_SNB_4BIT

#endif
