add_subdirectory(8bit_music)
add_subdirectory(adc)
add_subdirectory(blink)
add_subdirectory(rtc)
add_subdirectory(wwdg)
add_subdirectory(usart)
add_subdirectory(runtime)
add_subdirectory(scheduler)
add_subdirectory(dma_m2m)
add_subdirectory(iwdg)
add_subdirectory(mpu9250_spi_driver)
add_subdirectory(profiler)
add_subdirectory(pwm_led)
add_subdirectory(pwm_servo)
add_subdirectory(exti)

