#ifndef ARCH_MEMORYMAP_H
#define ARCH_MEMORYMAP_H

#define ARCH_SCS_BASE_ADDR (0xe000e000u)
#define ARCH_SCB_ADDR (ARCH_SCS_BASE_ADDR + 0x8)
#define ARCH_FPU_ADDR (ARCH_SCS_BASE_ADDR + 0xd88)
#define ARCH_MPU_ADDR (ARCH_SCS_BASE_ADDR + 0xd90)

/**
 * SysTick
 */
#define ARCH_SYSTICK_ADDR (ARCH_SCS_BASE_ADDR + 0x10)

#define ARCH_SYSTICK_CSR_ADDR (ARCH_SYSTICK_ADDR + 0x0)
#define ARCH_SYSTICK_RVR_ADDR (ARCH_SYSTICK_ADDR + 0x4)
#define ARCH_SYSTICK_CVR_ADDR (ARCH_SYSTICK_ADDR + 0x8)
#define ARCH_SYSTICK_CALR_ADDR (ARCH_SYSTICK_ADDR + 0xc)

/**
 * NVIC
 */
#define ARCH_NVIC_ADDR (ARCH_SCS_BASE_ADDR + 0x100)

#define ARCH_NVIC_ISER_ADDR (ARCH_NVIC_ADDR + 0x0)
#define ARCH_NVIC_ICER_ADDR (ARCH_NVIC_ADDR + 0x80)
#define ARCH_NVIC_ISPR_ADDR (ARCH_NVIC_ADDR + 0x100)
#define ARCH_NVIC_ICPR_ADDR (ARCH_NVIC_ADDR + 0x180)
#define ARCH_NVIC_IABR_ADDR (ARCH_NVIC_ADDR + 0x200)
#define ARCH_NVIC_IPR_ADDR (ARCH_NVIC_ADDR + 0x300)
#define ARCH_NVIC_STIR_ADDR (ARCH_NVIC_ADDR + 0xf00)

/**
 * Core System Control
 */
#define ARCH_CSC_ICTR_ADDR (ARCH_SCS_BASE_ADDR + 0x0)
#define ARCH_CSC_ICSR_ADDR (ARCH_SCS_BASE_ADDR + 0xd04)
#define ARCH_CSC_VTOR_ADDR (ARCH_SCS_BASE_ADDR + 0xd08)
#define ARCH_CSC_AIRCR_ADDR (ARCH_SCS_BASE_ADDR + 0xd0c)
#define ARCH_CSC_SCR_ADDR (ARCH_SCS_BASE_ADDR + 0xd10)
#define ARCH_CSC_CCR_ADDR (ARCH_SCS_BASE_ADDR + 0xd14)
#define ARCH_CSC_SHPR1_ADDR (ARCH_SCS_BASE_ADDR + 0xd18)
#define ARCH_CSC_SHPR2_ADDR (ARCH_SCS_BASE_ADDR + 0xd1c)
#define ARCH_CSC_SHPR3_ADDR (ARCH_SCS_BASE_ADDR + 0xd20)
#define ARCH_CSC_SHCSR_ADDR (ARCH_SCS_BASE_ADDR + 0xd24)
#define ARCH_CSC_CFSR_ADDR (ARCH_SCS_BASE_ADDR + 0xd28)
#define ARCH_CSC_HFSR_ADDR (ARCH_SCS_BASE_ADDR + 0xd2c)
#define ARCH_CSC_DFSR_ADDR (ARCH_SCS_BASE_ADDR + 0xd30)
#define ARCH_CSC_MMAR_ADDR (ARCH_SCS_BASE_ADDR + 0xd34)
#define ARCH_CSC_BFAR_ADDR (ARCH_SCS_BASE_ADDR + 0xd38)
#define ARCH_CSC_AFSR_ADDR (ARCH_SCS_BASE_ADDR + 0xd3c)

/**
 * Features
 */
#define ARCH_FTR_CPUID_ADDR (ARCH_SCS_BASE_ADDR + 0xd00)
#define ARCH_FTR_PFR0_ADDR (ARCH_SCS_BASE_ADDR + 0xd40)
#define ARCH_FTR_PFR1_ADDR (ARCH_SCS_BASE_ADDR + 0xd44)
#define ARCH_FTR_DFR0_ADDR (ARCH_SCS_BASE_ADDR + 0xd48)
#define ARCH_FTR_AFR0_ADDR (ARCH_SCS_BASE_ADDR + 0xd4c)
#define ARCH_FTR_MMFR0_ADDR (ARCH_SCS_BASE_ADDR + 0xd50)
#define ARCH_FTR_MMFR1_ADDR (ARCH_SCS_BASE_ADDR + 0xd54)
#define ARCH_FTR_MMFR2_ADDR (ARCH_SCS_BASE_ADDR + 0xd58)
#define ARCH_FTR_MMFR3_ADDR (ARCH_SCS_BASE_ADDR + 0xd5c)
#define ARCH_FTR_ISAR0_ADDR (ARCH_SCS_BASE_ADDR + 0xd60)
#define ARCH_FTR_ISAR1_ADDR (ARCH_SCS_BASE_ADDR + 0xd64)
#define ARCH_FTR_ISAR2_ADDR (ARCH_SCS_BASE_ADDR + 0xd68)
#define ARCH_FTR_ISAR3_ADDR (ARCH_SCS_BASE_ADDR + 0xd6c)
#define ARCH_FTR_ISAR4_ADDR (ARCH_SCS_BASE_ADDR + 0xd70)
#define ARCH_FTR_PID4_ADDR (ARCH_SCS_BASE_ADDR + 0xfd0)
#define ARCH_FTR_PID5_ADDR (ARCH_SCS_BASE_ADDR + 0xfd4)
#define ARCH_FTR_PID6_ADDR (ARCH_SCS_BASE_ADDR + 0xfd8)
#define ARCH_FTR_PID7_ADDR (ARCH_SCS_BASE_ADDR + 0xfdc)
#define ARCH_FTR_PID0_ADDR (ARCH_SCS_BASE_ADDR + 0xfe0)
#define ARCH_FTR_PID1_ADDR (ARCH_SCS_BASE_ADDR + 0xfe4)
#define ARCH_FTR_PID2_ADDR (ARCH_SCS_BASE_ADDR + 0xfe8)
#define ARCH_FTR_PID3_ADDR (ARCH_SCS_BASE_ADDR + 0xfec)
#define ARCH_FTR_CID0_ADDR (ARCH_SCS_BASE_ADDR + 0xff0)
#define ARCH_FTR_CID1_ADDR (ARCH_SCS_BASE_ADDR + 0xff4)
#define ARCH_FTR_CID2_ADDR (ARCH_SCS_BASE_ADDR + 0xff8)
#define ARCH_FTR_CID3_ADDR (ARCH_SCS_BASE_ADDR + 0xffc)

#define ARCH_ID_ADDR (ARCH_SCS_BASE_ADDR + 0xd40)

#endif
